pwlc/pwlc/Controllers/CheckupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using pwlc.Models;
using Microsoft.AspNet.Identity;

namespace pwlc.Controllers
{
    public class CheckupsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private DateTime birthday;

        //private DateTime? birthday;

        // GET: Checkups
        [Authorize(Roles = "Admin,Employee,Manager,Doctor")]
        public ActionResult Index()
        {
            return View(db.Checkups.ToList());
        }

        // GET: Checkups/Details/5
        [Authorize(Roles = "Admin,Employee,Manager,Doctor")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Checkup checkup = db.Checkups.Find(id);
            if (checkup == null)
            {
                return HttpNotFound();
            }
            return View(checkup);
        }

        // GET: Checkups/Create
        [Authorize(Roles = "Admin,Employee,Manager,Doctor")]
        public ActionResult Create(string pid)
        {
            if (pid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Patient patient = db.Patients.Find(pid);
            Checkup checkup = new Checkup();
            checkup.Patient = patient;
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(checkup);
        }

        // POST: Checkups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Audit]
        public ActionResult Create(Checkup checkup, Patient patient)
        {
            if (ModelState.IsValid)
            {
                checkup.Patient = db.Patients.Find(checkup.Patient.PatientId);
                DateTime now = DateTime.Today;
                birthday = DateTime.Parse(checkup.Patient.DateOfBirth);
                int age = now.Year - birthday.Year;
                checkup.Age = age;
                patient.Checkups.Add(checkup);
                db.Checkups.Add(checkup);
                db.SaveChanges();
                //if (checkup.ScriptToFill.ToString() == "Yes")
                //{
                //    return RedirectToAction("Create", "Prescriptions", new { /*cid = checkup.CheckupId,*/ pid = patient.PatientId });
                //}
                //return RedirectToAction("Create", "Invoices", new { cid = checkup.CheckupId });
                return RedirectToAction("Index");
            }

            return View(checkup);
        }

        // GET: Checkups/Edit/5
        [Authorize(Roles = "Admin,Employee,Manager,Doctor")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Checkup checkup = db.Checkups.Find(id);
            if (checkup == null)
            {
                return HttpNotFound();
            }
            return View(checkup);
        }

        // POST: Checkups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Audit]
        public ActionResult Edit([Bind(Include = "CheckupId,CheckupDate,Age,Height,Weight,BP,BMI,BodyFat,LossGain,Amount,TotalLoss,DailyWaterIntake,Cycle,Excercising,FollowingFoodGuidelines,HCG,Hips,Waist,Chest,Arm,ScriptToFill,FillScript,StaffNotes,DoctorNotes,Signature")] Checkup checkup)
        {
            if (ModelState.IsValid)
            {
                db.Entry(checkup).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(checkup);
        }

        // GET: Checkups/Delete/5
        [Authorize(Roles = "Admin,Employee,Manager,Doctor")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Checkup checkup = db.Checkups.Find(id);
            if (checkup == null)
            {
                return HttpNotFound();
            }
            return View(checkup);
        }

        // POST: Checkups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Audit]
        public ActionResult DeleteConfirmed(int id)
        {
            Checkup checkup = db.Checkups.Find(id);
            db.Checkups.Remove(checkup);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize(Roles = "Admin")]
        [Audit]
        public ActionResult AddSignature(int cid)
        {
            var holder = User.Identity.GetUserId();
            var user = db.Users.Where(s => s.Id == holder).FirstOrDefault();
            Checkup checkup = db.Checkups.Find(cid);
            checkup.Signature = "/Signature-Images/dr-test-doctor.png";
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        

    }
}

pwlc/pwlc/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using pwlc.Models;

namespace pwlc.Controllers
{
    public class EventsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Events
        [Authorize(Roles = "Admin,Employee,Manager,Doctor")]
        public ActionResult Index()
        {
            var events = db.Events.Include(a => a.AppointmentType);
            return View(events.ToList());
        }

        // GET: Events/Details/5
        [Authorize(Roles = "Admin,Employee,Manager,Doctor")]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // GET: Events/Create
        [Authorize(Roles = "Admin,Employee,Manager,Doctor")]
        public ActionResult Create(string pid)
        {
            if (pid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Patient patient = db.Patients.Find(pid);
            Event @event = new Event();
            @event.Patient = patient;
            @event.eventId = "APT-" + Guid.NewGuid().ToString();
            //@event.eventId = patient.Chart + "-" + Guid.NewGuid().ToString();
            @event.title = @event.Patient.FirstName + " " + @event.Patient.LastName;
            ViewBag.AppointmentTypeId = new SelectList(db.AppointmentTypes, "AppointmentTypeID", "ApptType");
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Event @event, DateTime StartDate, DateTime StartTime, AppointmentType AppointmentType, Patient patient)
        {

            if (ModelState.IsValid)
            {
                var chosenType = db.AppointmentTypes.Where(t => t.AppointmentTypeID == @event.AppointmentTypeId).First();
                var switchType = chosenType.ApptType.ToString();
                switch (switchType)
                {
                    case "New":
                        @event.description = "New Patient Appointment";
                        break;
                    case "Checkup":
                        @event.description = "Weekly Chekup Appointment";
                        break;
                    case "Restart":
                        @event.description = "Patient Restart Appointment";
                        break;
                    case "Other":
                        @event.description = "To Be Determined";
                        break;
                    default:
                        break;
                }
                //context.Entry(detachedModel).State = EntityState.Unchanged;
                @event.start = StartDate.ToString("yyyy-MM-dd ") + StartTime.ToString("HH:mm:ss");
                @event.color = chosenType.ApptColor;
                @event.borderColor = chosenType.ApptBorderColor;
                @event.textColor = chosenType.ApptTextColor;
                var minutesToAdd = chosenType.ApptDuration;
                var EndTime = StartTime + TimeSpan.FromMinutes(minutesToAdd);
                var EndDate = StartDate;
                @event.end = EndDate.ToString("yyyy-MM-dd ") + EndTime.ToString("HH:mm:ss");
                db.Events.Add(@event);
                db.Patients.Attach(@event.Patient);
                //db.Entry(patient).State = EntityState.Unchanged;
                //db.Entry(patient).State = EntityState.Modified;
                patient.Events.Add(@event);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AppointmentTypeId = new SelectList(db.AppointmentTypes, "AppointmentTypeID", "ApptType", @event.AppointmentTypeId);
            return View(@event);
        }

        // GET: Events/Edit/5
        [Authorize(Roles = "Admin,Employee,Manager,Doctor")]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            ViewBag.AppointmentTypeId = new SelectList(db.AppointmentTypes, "AppointmentTypeID", "ApptColor", @event.AppointmentTypeId);
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "eventId,title,description,start,end,color,borderColor,textColor,AppointmentTypeId")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AppointmentTypeId = new SelectList(db.AppointmentTypes, "AppointmentTypeID", "ApptColor", @event.AppointmentTypeId);
            return View(@event);
        }

        // GET: Events/Delete/5
        [Authorize(Roles = "Admin,Employee,Manager,Doctor")]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Event @event = db.Events.Find(id);
            db.Events.Remove(@event);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

pwlc/pwlc/Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using pwlc.Models;
using pwlc.Crypto;

namespace pwlc.Controllers
{
    public class PatientsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Patients
        [Authorize(Roles = "Admin,Employee,Manager,Doctor")]
        public ActionResult Index()
        {
            //var allPatients = db.Patients.ToList();
            //foreach (var patient in allPatients)
            //{
            //    patient.Address = Encryptor.Decrypt(patient.Address);
            //}
            //return View(allPatients);
            return View(db.Patients.ToList());
        }

        // GET: Patients/Details/5
        [Authorize(Roles = "Admin,Employee,Manager,Doctor")]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            patient.Address = Encryptor.Decrypt(patient.Address);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // GET: Patients/Create
        [Authorize(Roles = "Admin,Employee,Manager,Doctor")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Patients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PatientId,Chart,FirstName,LastName,Address,City,State,Zip,Phone,Email,DateOfBirth,ContactMethod")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                patient.PatientId = Guid.NewGuid().ToString();
                patient.Address = Encryptor.Encrypt(patient.Address);
                db.Patients.Add(patient);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(patient);
        }

        // GET: Patients/Edit/5
        [Authorize(Roles = "Admin,Employee,Manager,Doctor")]
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            patient.Address = Encryptor.Decrypt(patient.Address);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: Patients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PatientId,Chart,FirstName,LastName,Address,City,State,Zip,Phone,Email,DateOfBirth,ContactMethod")] Patient patient)
        {
            if (ModelState.IsValid)
            {
                patient.Address = Encryptor.Encrypt(patient.Address);
                db.Entry(patient).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(patient);
        }

        // GET: Patients/Delete/5
        [Authorize(Roles = "Admin,Employee,Manager,Doctor")]
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Patient patient = db.Patients.Find(id);
            db.Patients.Remove(patient);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        
    }
}

pwlc/pwlc/Views/Patients/Create.cshtml
@model pwlc.Models.Patient

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Patient</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PatientId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PatientId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PatientId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Chart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Chart, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Chart, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactMethod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.ContactMethod, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ContactMethod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

pwlc/pwlc/Views/Patients/Delete.cshtml
@model pwlc.Models.Patient

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Patient</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Chart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Chart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactMethod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactMethod)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

pwlc/pwlc/Views/Patients/GenerateLabel.cshtml
<p>
    @Html.ActionLink("Create Label", "GenerateRxLabel")
</p>

pwlc/pwlc/Views/Patients/Index.cshtml
@model IEnumerable<pwlc.Models.Patient>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<div id="patient">
    <div class="row">
        <div class="col-md-1"><h5>Chart</h5></div>
        <div class="col-md-2"><h5>Name</h5></div>
        <div class="col-md-2"><h5>Phone</h5></div>
        <div class="col-md-2"><h5>Email</h5></div>
        <div class="col-md-2"><h5>Contact Preference</h5></div>
        <div class="col-md-3"></div>
    </div>
    <hr />
    @foreach (var item in Model)
    {
        <div class="row">
            <div class="col-md-1">@Html.DisplayFor(modelItem => item.Chart)</div>
            <div class="col-md-2">@Html.DisplayFor(modelItem => item.FirstName) @Html.DisplayFor(modelItem => item.LastName)</div>
            <div class="col-md-2">@Html.DisplayFor(modelItem => item.Phone)</div>
            <div class="col-md-2">@Html.DisplayFor(modelItem => item.Email)</div>
            <div class="col-md-2">@Html.DisplayFor(modelItem => item.ContactMethod)</div>
            <div class="col-md-3">
                @Html.ActionLink("Edit", "Edit", new { id = item.PatientId }) |
                @Html.ActionLink("Details", "Details", new { id = item.PatientId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.PatientId }) |
                @Html.ActionLink("Add Checkup", "Create", "Checkups", new { pid = item.PatientId }, null) |
                @Html.ActionLink("Add Injection", "Create", "Injections", new { pid = item.PatientId }, null) |
                @Html.ActionLink("Add Appointment", "Create", "Events", new { pid = item.PatientId }, null)
            </div>
        </div>
    }
</div>

pwlc/pwlc/Views/Patients/Profile.cshtml
@{
    ViewBag.Title = "Profile";
}

<h2>Profile</h2>

pwlc/pwlc/Views/Patients/_PatientInfo.cshtml
@model IEnumerable<pwlc.Models.Patient>


<ul class="nav nav-pills">
    <li class="active"><a data-toggle="pill" href="#home">Patient Info</a></li>
    <li><a data-toggle="pill" href="#menu1">Checkups</a></li>
    <li><a data-toggle="pill" href="#menu2">Injections</a></li>
    <li><a data-toggle="pill" href="#menu2">Invoices</a></li>
</ul>

<div class="tab-content">
    <div id="home" class="tab-pane fade in active">
        <h3>HOME</h3>
        <p>Home content</p>
    </div>
    <div id="menu1" class="tab-pane fade">
        <h3>Menu 1</h3>
        <p>Some content in menu 1.</p>
    </div>
    <div id="menu2" class="tab-pane fade">
        <h3>Menu 2</h3>
        <p>Some content in menu 2.</p>
    </div>
</div>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Chart)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Zip)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactMethod)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
            {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Chart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zip)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactMethod)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.PatientId }) |
                @Html.ActionLink("Details", "Details", new { id = item.PatientId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.PatientId }) |
                @Html.ActionLink("Add Checkup", "Create", "Checkups", new { pid = item.PatientId }, null) |
                @Html.ActionLink("Add Injection", "Create", "Injections", new { pid = item.PatientId }, null) |
                @Html.ActionLink("Add Appointment", "Create", "Events", new { pid = item.PatientId }, null)
            </td>
        </tr>
    }

</table>